
package jaxWS.VendaWS;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaWS", targetNamespace = "http://jaxWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VendaWS")
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "VendaWS", targetNamespace = "http://jaxWS/", className = "jaxWS.VendaWS.VendaWS_Type")
    @ResponseWrapper(localName = "VendaWSResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.VendaWS.VendaWSResponse")
    public String vendaWS();

}
