
package jaxWS.EntregaWS;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaWS", targetNamespace = "http://jaxWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EntregaWS")
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "EntregaWS", targetNamespace = "http://jaxWS/", className = "jaxWS.EntregaWS.EntregaWS_Type")
    @ResponseWrapper(localName = "EntregaWSResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.EntregaWS.EntregaWSResponse")
    public String entregaWS();

}
