
package jaxWS.ProdutoWS;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebService(name = "ProdutoWS", targetNamespace = "http://jaxWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoWS {


    /**
     *
     * @param codigo
     * @param id
     * @param preco
     * @param nome
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProdutoWSAtualizar")
    @WebResult(name = "ProdutoWSAtualizarResult", targetNamespace = "")
    @RequestWrapper(localName = "ProdutoWSAtualizar", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSAtualizar")
    @ResponseWrapper(localName = "ProdutoWSAtualizarResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSAtualizarResponse")
    public String produtoWSAtualizar(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco);

    /**
     *
     * @param codigo
     * @param preco
     * @param nome
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProdutoWSCriar")
    @WebResult(name = "ProdutoWSCriarResult", targetNamespace = "")
    @RequestWrapper(localName = "ProdutoWSCriar", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSCriar")
    @ResponseWrapper(localName = "ProdutoWSCriarResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSCriarResponse")
    public String produtoWSCriar(
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco);

    /**
     *
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProdutoWSLer")
    @WebResult(name = "ProdutoWSLerResult", targetNamespace = "")
    @RequestWrapper(localName = "ProdutoWSLer", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSLer")
    @ResponseWrapper(localName = "ProdutoWSLerResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSLerResponse")
    public String produtoWSLer(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     *
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProdutoWSApagar")
    @WebResult(name = "ProdutoWSApagarResult", targetNamespace = "")
    @RequestWrapper(localName = "ProdutoWSApagar", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSApagar")
    @ResponseWrapper(localName = "ProdutoWSApagarResponse", targetNamespace = "http://jaxWS/", className = "jaxWS.ProdutoWS.ProdutoWSApagarResponse")
    public String produtoWSApagar(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
