
package jaxWS.ProdutoWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProdutoWSService", targetNamespace = "http://jaxWS/", wsdlLocation = "http://localhost:8080/lab141116/ProdutoWS?wsdl")
public class ProdutoWSService
    extends Service
{

    private final static URL PRODUTOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUTOWSSERVICE_EXCEPTION;
    private final static QName PRODUTOWSSERVICE_QNAME = new QName("http://jaxWS/", "ProdutoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab141116/ProdutoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUTOWSSERVICE_WSDL_LOCATION = url;
        PRODUTOWSSERVICE_EXCEPTION = e;
    }

    public ProdutoWSService() {
        super(__getWsdlLocation(), PRODUTOWSSERVICE_QNAME);
    }

    public ProdutoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUTOWSSERVICE_QNAME, features);
    }

    public ProdutoWSService(URL wsdlLocation) {
        super(wsdlLocation, PRODUTOWSSERVICE_QNAME);
    }

    public ProdutoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUTOWSSERVICE_QNAME, features);
    }

    public ProdutoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdutoWS
     */
    @WebEndpoint(name = "ProdutoWSPort")
    public ProdutoWS getProdutoWSPort() {
        return super.getPort(new QName("http://jaxWS/", "ProdutoWSPort"), ProdutoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdutoWS
     */
    @WebEndpoint(name = "ProdutoWSPort")
    public ProdutoWS getProdutoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxWS/", "ProdutoWSPort"), ProdutoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUTOWSSERVICE_EXCEPTION!= null) {
            throw PRODUTOWSSERVICE_EXCEPTION;
        }
        return PRODUTOWSSERVICE_WSDL_LOCATION;
    }

}
